### ISSUE TITLE
Experiment with React

### ISSUE THREAD

**Issue by Sk3tch7y** [Sk3tch7y/Intercal#10]

**Comment by OakleyPankratz** [comment]
I read the document found on https://react.dev/learn. I plan to re-read these sections to strengthen my grasp of the concepts before we begin our next issues. Moreover, I learnt JavaScript, including basic syntax, functions, and arrays/typed arrays by working on some coding problems related to data-manipulation. Again, to do a little extra for this issue, I plan to watch https://www.youtube.com/watch?v=rLPwCAqyCAE to see how JavaScript handles OOP.
